/**
 * App layout
 * Next.js root layout component for the App Router. Wraps pages with header and global styles.
 */

import type { Metadata } from "next";
// dynamic import removed; using ClientShell client wrapper instead
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClientShell } from "@/components";
import Link from "next/link";
import DetailsMenu from "@/components/DetailsMenu";
import UserProfileMenuClient from "@/components/UserProfileMenuClient";
import { CartCountBadge } from "@/components";
import {
  PageThemeProvider,
  PageThemeSwitcher,
} from "@/components/PageThemeContext";
import { Toaster } from "react-hot-toast";
import { getServerSession } from "@/lib/getServerSession";
import { MobileNav } from "@/components/MobileNav";
import type { Session } from "better-auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Sign-out behavior is provided by the client component `SignOutButton` to
// avoid calling client-only APIs from server components. See
// `src/components/SignOutButton.tsx` for the implementation.

// session user role typing is provided by better-auth augmentation

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = (await getServerSession()) as Session | null;

  // no role-based checks here; use `session` truthiness for auth-aware UI

  const navLinks = [
    { href: "/movies", label: "Movies" },
    { href: "/persons", label: "People" },
    {
      label: "Collections",
      children: [
        { href: "/collections/new", label: "New Releases" },
        { href: "/collections/top-rated", label: "Top Rated" },
        { href: "/collections/top-selling", label: "Top Selling" },
        { href: "/collections/classics", label: "All-Time Classics" },
        { href: "/collections/budget", label: "Budget Friendly" },
        { href: "/collections/genres", label: "By Genre" },
      ],
    },
    // About link moved to footer
  ];

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        <a
          href="#main-content-start"
          className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50 focus:bg-white/90 focus:dark:bg-gray-900/80 focus:text-indigo-600 focus:px-3 focus:py-2 rounded"
        >
          Skip to content
        </a>
        {/* Server-rendered skip target so accessibility scanners can find an anchor
            even when the actual main content is rendered inside a client wrapper. */}
        <div id="main-content-start" tabIndex={-1} />
        <Toaster position="top-center" reverseOrder={false} />
        <ClientShell serverSession={session}>
          <PageThemeProvider>
            <div className="flex flex-col min-h-screen">
              <header
                role="banner"
                className="sticky top-0 z-50 backdrop-blur-md bg-card border-b border-border shadow-sm"
              >
                <div className="max-w-7xl mx-auto flex flex-wrap items-center gap-3 px-4 py-3">
                  <Link
                    href="/"
                    aria-label="MovieShop home"
                    className="flex items-center gap-3"
                  >
                    <span className="tracking-tight font-extrabold text-base md:text-lg lg:text-2xl bg-clip-text text-transparent bg-linear-to-r from-indigo-600 via-purple-500 to-pink-400">
                      MovieShop
                    </span>
                  </Link>

                  <nav
                    className="hidden md:flex items-center gap-4 ml-6 text-sm"
                    role="navigation"
                    aria-label="Main navigation"
                  >
                    {navLinks.map((link) =>
                      link.children ? (
                        <DetailsMenu
                          key={link.label}
                          className="group relative"
                          summary={
                            <summary className="cursor-pointer list-none flex items-center gap-2 px-3 py-1 rounded-md text-sm main-nav-link transition focus:outline-none focus:ring-2 focus:ring-blue-300/40">
                              <span>{link.label}</span>
                              <svg
                                className="w-3 h-3 opacity-80 transition-transform duration-150 group-open:rotate-180"
                                xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                              >
                                <path
                                  d="M6 9l6 6 6-6"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeWidth="2"
                                />
                              </svg>
                            </summary>
                          }
                        >
                          <div className="absolute top-full mt-2 w-48 bg-card border border-border rounded-md shadow-lg py-1 z-10">
                            {link.children.map((child) => (
                              <Link
                                key={child.href}
                                href={child.href}
                                className="block px-4 py-2 text-sm text-foreground hover:bg-accent hover:text-accent-foreground first:rounded-t-md last:rounded-b-md mx-1 my-1 transition"
                              >
                                {child.label}
                              </Link>
                            ))}
                          </div>
                        </DetailsMenu>
                      ) : (
                        <Link
                          key={link.href}
                          href={link.href!}
                          className="inline-flex items-center gap-2 px-3 py-2 rounded-md text-sm main-nav-link transition focus:outline-none focus:ring-2 focus:ring-blue-300/40"
                        >
                          {link.label}
                        </Link>
                      ),
                    )}
                    {/* Admin moved into user menu for desktop */}
                  </nav>

                  <div className="grow" />

                  <div className="hidden md:flex items-center gap-4">
                    {session ? (
                      <>
                        <UserProfileMenuClient
                          name={session.user?.name}
                          showAdmin={Boolean(session)}
                        />
                      </>
                    ) : (
                      <>
                        <Link
                          href="/sign-in"
                          className="px-4 py-2 rounded-md text-sm font-semibold bg-primary text-primary-foreground hover:bg-primary/90 shadow-md"
                        >
                          Sign In
                        </Link>
                        <Link
                          href="/sign-up"
                          className="px-4 py-2 rounded-md text-sm font-semibold bg-linear-to-r from-emerald-500 to-emerald-600 text-white shadow-md hover:brightness-95 transition focus:outline-none focus:ring-2 focus:ring-emerald-300/40"
                        >
                          Sign Up
                        </Link>
                      </>
                    )}
                  </div>

                  <Link
                    href="/cart"
                    className="inline-flex items-center gap-2 px-3 py-2 rounded-md text-sm hover:bg-slate-100 dark:hover:bg-popover focus:outline-none focus:ring-2 focus:ring-blue-300/40"
                    aria-label="View cart"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 24 24"
                      className="w-6 h-6 text-emerald-600 dark:text-emerald-400"
                      aria-hidden
                    >
                      <path
                        d="M3 3h2l1.6 9.6A2 2 0 0 0 8.5 15h9a2 2 0 0 0 1.95-1.58L21 6H6"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                      <circle cx="10" cy="19" r="1.5" fill="currentColor" />
                      <circle cx="18" cy="19" r="1.5" fill="currentColor" />
                    </svg>
                    <CartCountBadge />
                  </Link>
                  <PageThemeSwitcher />
                  <MobileNav session={session} navLinks={navLinks} />
                </div>
              </header>

              <main
                id="main-content"
                tabIndex={-1}
                className="grow container mx-auto px-4 sm:px-6 lg:px-8 py-6"
              >
                <div className="bg-card backdrop-blur-sm rounded-xl shadow-lg p-4 sm:p-6 md:p-10">
                  {children}
                </div>
              </main>

              <footer className="bg-secondary backdrop-blur-sm border-t border-border py-4 px-4 sm:px-6 lg:px-8">
                <div className="max-w-7xl mx-auto flex flex-col sm:flex-row justify-between items-center text-sm text-muted-foreground">
                  <p>
                    &copy; {new Date().getFullYear()} MovieShop — Tarek Aarachi
                  </p>
                  <div className="flex-1 text-center hidden md:block">
                    A demo storefront using Next.js, Prisma, and Better Auth.
                  </div>
                  <nav className="flex items-center gap-3">
                    <Link
                      href="/privacy"
                      className="inline-flex items-center gap-2 px-3 py-1 rounded-md text-sm bg-linear-to-r from-sky-700/10 via-blue-600/8 to-indigo-700/10 hover:from-sky-500/40 hover:via-blue-500/30 hover:to-indigo-500/40 active:scale-95 active:from-sky-400/60 transition transform duration-150 ease-out focus:outline-none focus:ring-2 focus:ring-blue-400"
                    >
                      Privacy
                    </Link>
                    <Link
                      href="/contact"
                      className="inline-flex items-center gap-2 px-3 py-1 rounded-md text-sm bg-linear-to-r from-sky-700/10 via-blue-600/8 to-indigo-700/10 hover:from-sky-500/40 hover:via-blue-500/30 hover:to-indigo-500/40 active:scale-95 active:from-sky-400/60 transition transform duration-150 ease-out focus:outline-none focus:ring-2 focus:ring-blue-400"
                    >
                      Contact
                    </Link>
                    <Link
                      href="/about"
                      className="inline-flex items-center gap-2 px-3 py-1 rounded-md text-sm bg-linear-to-r from-sky-700/10 via-blue-600/8 to-indigo-700/10 hover:from-sky-500/40 hover:via-blue-500/30 hover:to-indigo-500/40 active:scale-95 active:from-sky-400/60 transition transform duration-150 ease-out focus:outline-none focus:ring-2 focus:ring-blue-400"
                    >
                      About
                    </Link>
                  </nav>
                </div>
              </footer>
            </div>
          </PageThemeProvider>
        </ClientShell>
      </body>
    </html>
  );
}
