import type { Metadata } from "next";
import { CartCountProvider } from "@/components/CartCountContext";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBarClient from "@/components/NavBarClient";
// ...existing code...
import SonnerProvider from "@/app/SonnerProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="font-sans min-h-screen flex flex-col bg-gradient-to-b from-gray-900 via-gray-800 to-gray-900 text-gray-100">
        <SonnerProvider />
        <CartCountProvider>
          <header className="bg-gray-800 shadow-lg">
            <NavBarClient />
          </header>
          <main className="flex-1">{children}</main>
          <footer className="p-4 border-t border-gray-700 bg-gray-800 text-center text-gray-400">
            <span className="text-sm tracking-wide">
              © 2025 Fullstack -{" "}
              <span className="font-semibold text-teal-400">Js React G13</span>{" "}
              | <span className="font-semibold text-teal-400">Delta Team</span>{" "}
              - Lexicon AB
            </span>
          </footer>
        </CartCountProvider>
      </body>
    </html>
  );
}
